export const StudentStatus = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
} as const;

export const InvoiceStatus = {
  DRAFT: "DRAFT",
  PENDING_PAYMENT: "PENDING_PAYMENT",
  PAID: "PAID",
  CANCELLED: "CANCELLED",
  EXPIRED: "EXPIRED",
} as const;

export const PaymentStatus = {
  INITIATED: "INITIATED",
  QR_GENERATED: "QR_GENERATED",
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED",
} as const;

export const PeriodStatus = {
  ACTIVE: "ACTIVE",
  CLOSED: "CLOSED",
} as const;

export const QrStatus = {
  ACTIVE: "ACTIVE",
  EXPIRED: "EXPIRED",
  USED: "USED",
  CANCELLED: "CANCELLED",
} as const;

export const AdminRole = {
  ADMIN: "ADMIN",
  FINANCE: "FINANCE",
} as const;

export const UserType = {
  STUDENT: "STUDENT",
  ADMIN: "ADMIN",
} as const;

export const AuditAction = {
  STUDENT_REGISTER: "STUDENT_REGISTER",
  STUDENT_LOGIN: "STUDENT_LOGIN",
  ADMIN_LOGIN: "ADMIN_LOGIN",
  PASSWORD_RESET: "PASSWORD_RESET",
  PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
  INVOICE_CREATED: "INVOICE_CREATED",
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_QR_GENERATED: "PAYMENT_QR_GENERATED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_RECONCILIATION: "PAYMENT_RECONCILIATION",
  FEE_CHANGED: "FEE_CHANGED",
  STUDENT_UPDATED: "STUDENT_UPDATED",
  PERIOD_CHANGED: "PERIOD_CHANGED",
  SUBJECT_CHANGED: "SUBJECT_CHANGED",
  SESSION_CHANGED: "SESSION_CHANGED",
} as const;

export const CURRENCY = "LKR";
